// generate-exports.js
const fs = require('fs');
const path = require('path');

const outputsPath = path.resolve(__dirname, 'cdk-outputs.json');
const reactPath = path.resolve(__dirname, 'frontend/react-app', 'src', 'aws-exports.js');

if (!fs.existsSync(outputsPath)) {
  console.error("cdk-outputs.json not found. Run `cdk deploy --outputs-file cdk-outputs.json` first.");
  process.exit(1);
}

const outputs = require(outputsPath);

// Adjust this to match your actual stack name
const stackOutputs = outputs["AwsLexChatbotStack"];
if (!stackOutputs) {
  console.error("No outputs found for AwsLexChatbotStack.");
  process.exit(1);
}

const configContent = `// Auto-generated by generate-exports.js
export const awsConfig = {
  bookingApiUrl: "${stackOutputs.REACTAPPBOOKINGAPI}",
  availabilityApiUrl: "${stackOutputs.REACTAPPAVAILABILITYAPI}",
  lexBotArn: "${stackOutputs.REACTAPPLEXBOTARN}"
};
export default awsConfig
`;

fs.writeFileSync(reactPath, configContent);
console.log("aws-exports.js has been updated.");
