// Auto-generated by generate-exports.js
export const awsConfig = {
  bookingApiUrl:      "https://b6j6wx5k8h.execute-api.eu-west-2.amazonaws.com/prod/",
  availabilityApiUrl: "https://oponbxh4s1.execute-api.eu-west-2.amazonaws.com/prod/",
  lexBotArn:          "arn:aws:lex:eu-west-2:112479509543:bot/H3I1EEFVRT",
  lexBotName:         "MeetingBookingBot",
  lexBotRegion:       "eu-west-2",
  lexBotId:           "H3I1EEFVRT",       // new Lex V2 botId
  lexBotAliasId:      "RSDEOYUWX0|H3I1EEFVRT", // new Lex V2 aliasId
  lexBotLocaleId:     "en_US"                                    // default locale
};
export default awsConfig;
