// Auto-generated by generate-exports.js
export const awsConfig = {
  bookingApiUrl:      "https://mihd1nks54.execute-api.eu-west-2.amazonaws.com/prod/",
  availabilityApiUrl: "https://00k93e0uv3.execute-api.eu-west-2.amazonaws.com/prod/",
  lexBotArn:          "arn:aws:lex:eu-west-2:112479509543:bot/SYFRTACM27",
  lexBotName:         "MeetingBookingBot",
  lexBotRegion:       "eu-west-2",
  lexBotId:           "SYFRTACM27",       // new Lex V2 botId
  lexBotAliasId:      "PVN4KW9CRR|SYFRTACM27", // new Lex V2 aliasId
  lexBotLocaleId:     "en_US"                                    // default locale
};
export default awsConfig;
