// Auto-generated by generate-exports.js
export const awsConfig = {
  bookingApiUrl:      "https://xcwal1xr4m.execute-api.eu-west-2.amazonaws.com/prod/",
  availabilityApiUrl: "https://w6i8smohfb.execute-api.eu-west-2.amazonaws.com/prod/",
  lexBotArn:          "arn:aws:lex:eu-west-2:112479509543:bot/YGMRNMWRHO",
  lexBotName:         "MeetingBookingBot",
  lexBotRegion:       "eu-west-2"
};
export default awsConfig;
